Create	a	null	vector	of	size	20	but	the	10th value	of	20

In [156]:
import numpy as np
import pandas as pd 

array = np.eye( 20 ) [ 10 - 1 ] *20
print(array)

[ 0.  0.  0.  0.  0.  0.  0.  0.  0. 20.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.]


In [157]:
my_vect = np.zeros(20)
# set index 10 value 1
my_vect[np.array([10])] = 20
print(my_vect)

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0. 20.  0.  0.  0.  0.  0.  0.  0.
  0.  0.]


Create	a	vector	of	positive	odd	integers	less	than	100.	Remove	the	values	greater	than	60	and	less	than	80

In [158]:
#Vector of odd number from 1 till 99 
q2_vect = np.arange(1,100,2)
print("Original Vector:", q2_vect)
#Filter values to exclude number greater then 60 and less than 80
q2_vect_final = q2_vect[np.where((q2_vect >= 80) | (q2_vect <=60))]
print("Filtered vector: ",q2_vect_final)

Original Vector: [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]
Filtered vector:  [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 81 83 85 87 89 91 93 95 97 99]


In [159]:
#Find the mean, standard deviation of the resulting vector in Q2

In [160]:
print("Mean of Vector:" , q2_vect_final.mean())
print("Standard Deviation:", q2_vect_final.std())

Mean of Vector: 45.0
Standard Deviation: 30.133038346638727


Consider the following vector of values. X <-{8, 14, 9, 15, NA, 8,13, 2,9, NA} . Find the positions of the missing values and how many are there

In [161]:
X = np.array([8, 14, 9, 15, None , 8,13, 2,9, None])
print("Original vector: ", X)
boolArr = (X == None)
result = np.where(boolArr)
print("Position where NaN is in the list: ", result)
print("Number of NnN:", len(X[boolArr]))
print("Number of NnN(Alternate):", np.sum(boolArr))

Original vector:  [8 14 9 15 None 8 13 2 9 None]
Position where NaN is in the list:  (array([4, 9]),)
Number of NnN: 2
Number of NnN(Alternate): 2


Create two matrices from the given vectors
X1 = {2,3,7,1,6,2,3,5,1} and X2 = {3,2,9,0,7,8,5,8,2}. Find the matrix product.

In [162]:
X1 = np.array([2,3,7,1,6,2,3,5,1])
X2 = np.array([3,2,9,0,7,8,5,8,2])
X11 = X1.reshape(3,3)
X22 = X2.reshape(3,3)
print(np.matmul(X11,X22))

[[41 81 56]
 [13 60 61]
 [14 49 69]]


From the string:"Silver Gold Copper Platinum"
Use str.split, a loop, string manipulation and str.join to create the following sentence. 
Notice that the metals are in alphabetical order. "Copper and gold and platinum and silver are only worth money."

In [163]:
str_text = "Silver Gold Copper Platinum"
sentence = str.split(str_text, ' ')
sentence.sort()
sent_str = ""
for i in sentence:
    sent_str += str(i) + " and "

sent_str = sent_str[:-4] + "are only worth money."
print (sent_str)

Copper and Gold and Platinum and Silver are only worth money.


`x` and `y` are integers 
x=[-10-9-8-7-6-5-4-3-2-1 0
1 2 3 4 5 6 7 89] 
y =[-10-9-8-7-6-5-4-3-2-1 0
1 2 3 4 5 6 7 89]
• If x is from 1 to 4, add one to y.
• If x is not 1,2,3,4,5,6,or 7,make y equal to 7.
• For what values of x are the following true? 
. x>0 and x<3
• x<=0 or x>=3

In [164]:
x = np.array([-10,-9,-8,-7,-6,-5,-4,-3,-2,-1, 0, 1, 2, 3, 4, 5, 6, 7, 8,9])
y = np.array([-10,-9,-8,-7,-6,-5,-4,-3,-2,-1, 0, 1, 2, 3, 4, 5, 6, 7, 8,9])
not_x = np.array([1,2,3,4,5,6,7])
y1 = np.array(y)
y2 = np.array(y)

print("Total Number of x Values between 1 and 4:", y[np.where((x > 0 ) & (x <= 4))])
y1[np.where((x > 0 ) & (x <= 4))] = (y1[np.where((x > 0 ) & (x <= 4))] + 1)
print("Added 1 to Original value of Y where condition met:", y1)

#If x is not 1,2,3,4,5,6,or 7,make y equal to 7.
y2[np.where(np.in1d(x,not_x))] = 7
print("Updated List with y Value as 7", y2)

x1 = np.array(x[np.where((x > 0 ) & (x < 3))])
print("x > 0 and x < 3: " , x1)
x2 = np.array(x[np.where((x >= 3 ) | (x <= 0))])
print("x <= 0 or x >= 3: " , x2)


Total Number of x Values between 1 and 4: [1 2 3 4]
Added 1 to Original value of Y where condition met: [-10  -9  -8  -7  -6  -5  -4  -3  -2  -1   0   2   3   4   5   5   6   7
   8   9]
Updated List with y Value as 7 [-10  -9  -8  -7  -6  -5  -4  -3  -2  -1   0   7   7   7   7   7   7   7
   8   9]
x > 0 and x < 3:  [1 2]
x <= 0 or x >= 3:  [-10  -9  -8  -7  -6  -5  -4  -3  -2  -1   0   3   4   5   6   7   8   9]


Make a 5 x 8 Numpy array of random integers from 1 - 10. 
Iterate through each row of your array and report the rows where the numbers add to an even number.

In [165]:
import random
N = 5
M = 8
random.seed(1)
[[random.random()]*M for x in range(N)]
k = np.random.randint(1,10,(M,N))
print("5 X 8 Array: ", k)

sum_array = np.sum(k,axis = 1)
print("Sum Of Rows", sum_array)
print("Rows with sum of all numbers are even :", np.where((sum_array % 2) == 0))

5 X 8 Array:  [[1 3 6 8 4]
 [4 7 2 5 6]
 [4 1 7 8 7]
 [8 9 9 7 4]
 [7 2 1 8 5]
 [1 7 4 1 4]
 [8 5 6 1 8]
 [2 8 7 9 5]]
Sum Of Rows [22 24 27 37 23 17 28 31]
Rows with sum of all numbers are even : (array([0, 1, 6]),)


Write a function that accumulates into a list, 5 lotto picks. Each lotto pick is a `list` of 6 numbers from 1 to 52, with no repeats. Present them sorted, and printed them like this: Your lotto picks:
6, 9, 10, 29, 37, 43
1, 2, 10, 29, 31, 32
4, 16, 22, 39, 43, 44 
4, 10, 12, 28, 37, 44 
15, 16, 22, 24, 49, 52

In [166]:
# n is number of lotto picks
def lotto_pick(n):
    i  = 0
    pick_list = []
    while(i <= n):
        pick = np.random.choice(range(1,52),6,replace=False)
        pick.sort()
        pick_list.append(pick)
        i = i + 1
    return pick_list
    
retrun_list = lotto_pick(5)
#Below line will print Matrix with [] around the values
print("Matrix Print: ", np.matrix(retrun_list))

# Below will print desired value as per question
for row in retrun_list:
    k = ', '.join([str(elem) for elem in row])
    print(k)

Matrix Print:  [[ 4 10 12 21 32 46]
 [ 2 12 23 28 32 51]
 [ 1  7 25 29 37 51]
 [ 5  8 12 16 20 29]
 [ 2  8 12 30 33 43]
 [10 18 31 37 39 43]]
4, 10, 12, 21, 32, 46
2, 12, 23, 28, 32, 51
1, 7, 25, 29, 37, 51
5, 8, 12, 16, 20, 29
2, 8, 12, 30, 33, 43
10, 18, 31, 37, 39, 43
